# Generated by Django 5.1.7 on 2025-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatallocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
